# Generated by Django 3.2.5 on 2021-07-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('mobile', models.CharField(max_length=60)),
                ('country', models.CharField(max_length=60)),
                ('gender', models.CharField(max_length=60)),
                ('birth_month', models.CharField(max_length=60)),
                ('birth_year', models.CharField(max_length=60)),
                ('address1', models.CharField(max_length=60)),
                ('address2', models.CharField(max_length=60)),
                ('prev_qualification', models.CharField(max_length=60)),
                ('IELTSBand', models.CharField(max_length=60)),
                ('Desiredlevel', models.CharField(max_length=60)),
                ('StudyDestination', models.CharField(max_length=60)),
                ('IntendedSemester', models.CharField(max_length=60)),
                ('DesiredSubject', models.CharField(max_length=60)),
            ],
        ),
    ]
