# Generated by Django 3.2.5 on 2021-08-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('role', models.CharField(max_length=60)),
                ('agency_name', models.CharField(max_length=60)),
                ('country', models.CharField(max_length=60)),
                ('mobile', models.CharField(max_length=60)),
                ('website', models.CharField(max_length=60)),
                ('address2', models.CharField(max_length=60)),
                ('offices', models.CharField(max_length=60)),
                ('subagents', models.CharField(max_length=60)),
                ('YearFounded', models.CharField(max_length=60)),
                ('number_of_staff', models.CharField(max_length=60)),
                ('services_provided', models.CharField(max_length=60)),
                ('students_sent_abroad', models.CharField(max_length=60)),
                ('association_bin', models.CharField(max_length=60)),
                ('associations', models.CharField(max_length=60)),
                ('recruitment_area', models.CharField(max_length=60)),
                ('charge', models.CharField(max_length=60)),
            ],
        ),
    ]
