# Generated by Django 3.2.5 on 2021-08-14 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_agents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=60)),
                ('mobile', models.CharField(max_length=60)),
                ('country', models.CharField(max_length=60)),
                ('UGfee', models.CharField(max_length=60)),
                ('PGfee', models.CharField(max_length=60)),
                ('Diplomafee', models.CharField(max_length=60)),
                ('AccomodationCost', models.CharField(max_length=60)),
                ('FallSemester', models.CharField(max_length=60)),
                ('SpringSemester', models.CharField(max_length=60)),
                ('SummerSemester', models.CharField(max_length=60)),
                ('ranking', models.CharField(max_length=60)),
            ],
        ),
    ]
