# Generated by Django 3.2.5 on 2021-08-15 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_uni'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uni',
            old_name='university_name',
            new_name='name',
        ),
    ]
