# Generated by Django 3.2.5 on 2021-09-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0012_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='agents',
            name='email',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='email',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='email',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
