# Generated by Django 3.2.5 on 2021-09-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0013_auto_20210916_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='email',
        ),
        migrations.AddField(
            model_name='uni',
            name='email',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
