# Generated by Django 3.2.5 on 2021-11-03 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0014_auto_20210916_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=60)),
                ('applied_intake_date', models.CharField(blank=True, max_length=60, null=True)),
                ('client_phone', models.CharField(blank=True, max_length=60, null=True)),
                ('client_assignee', models.CharField(blank=True, max_length=60, null=True)),
                ('application_assignee', models.CharField(blank=True, max_length=60, null=True)),
                ('product', models.CharField(blank=True, max_length=60, null=True)),
                ('partner', models.CharField(blank=True, max_length=60, null=True)),
                ('partner_branches', models.CharField(blank=True, max_length=60, null=True)),
                ('partners_client_id', models.CharField(blank=True, max_length=60, null=True)),
                ('work_flow', models.CharField(blank=True, max_length=60, null=True)),
                ('application_start_by', models.CharField(blank=True, max_length=60, null=True)),
                ('application_start_by_branch', models.CharField(blank=True, max_length=60, null=True)),
                ('status', models.CharField(blank=True, max_length=60, null=True)),
                ('stage_in_queue', models.CharField(blank=True, max_length=60, null=True)),
                ('created_at', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IELTSCert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='post_images')),
            ],
        ),
        migrations.CreateModel(
            name='LatestDegree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='post_images')),
            ],
        ),
    ]
