# Generated by Django 3.2.5 on 2021-11-04 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0015_application_ieltscert_latestdegree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ieltscert',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images'),
        ),
        migrations.AlterField(
            model_name='latestdegree',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images'),
        ),
    ]
