# Generated by Django 3.2.5 on 2021-11-07 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0016_auto_20211104_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentCert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_images')),
            ],
        ),
    ]
