# Generated by Django 3.2.5 on 2021-12-14 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0019_program'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unilogo',
            old_name='mobile',
            new_name='email',
        ),
    ]
