# Generated by Django 3.2.5 on 2021-12-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0020_rename_mobile_unilogo_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='uni',
            name='IELTSRequirement',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
