# Generated by Django 3.2.5 on 2021-12-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0021_uni_ieltsrequirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='added_by',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
