# Generated by Django 3.2.5 on 2021-12-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0022_students_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='agents',
            name='added_by',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
