# Generated by Django 3.2.5 on 2021-12-30 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0024_auto_20211230_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='agents',
            name='active_status',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
