# Generated by Django 3.2.5 on 2022-01-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0027_auto_20220119_0855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uni',
            old_name='AccomodationCost',
            new_name='AccomodationCostPG',
        ),
        migrations.AddField(
            model_name='uni',
            name='AccomodationCostUG',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='uni',
            name='PGAppfee',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='uni',
            name='PGDuolingoReq',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='uni',
            name='PGIELTSReq',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='uni',
            name='PGPTEReq',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='uni',
            name='PGTOEFLReq',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='uni',
            name='UGAppfee',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='uni',
            name='UGDuolingoReq',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='uni',
            name='UGIELTSReq',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='uni',
            name='UGPTEReq',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='uni',
            name='UGTOEFLReq',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
