# Generated by Django 3.2.5 on 2022-01-19 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0028_auto_20220119_1404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uni',
            old_name='IELTSRequirement',
            new_name='HSCReq',
        ),
    ]
