# Generated by Django 3.2.5 on 2022-01-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0029_rename_ieltsrequirement_uni_hscreq'),
    ]

    operations = [
        migrations.AddField(
            model_name='uni',
            name='ScholarshipReq',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
