# Generated by Django 3.2.5 on 2022-01-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0030_uni_scholarshipreq'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('role', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('mobile', models.CharField(max_length=60)),
                ('student_c', models.CharField(blank=True, max_length=60, null=True)),
                ('student_r', models.CharField(blank=True, max_length=60, null=True)),
                ('student_u', models.CharField(blank=True, max_length=60, null=True)),
                ('student_d', models.CharField(blank=True, max_length=60, null=True)),
                ('agent_c', models.CharField(blank=True, max_length=60, null=True)),
                ('agent_r', models.CharField(blank=True, max_length=60, null=True)),
                ('agent_u', models.CharField(blank=True, max_length=60, null=True)),
                ('agent_d', models.CharField(blank=True, max_length=60, null=True)),
                ('service_provider_c', models.CharField(blank=True, max_length=60, null=True)),
                ('service_provider_r', models.CharField(blank=True, max_length=60, null=True)),
                ('service_provider_u', models.CharField(blank=True, max_length=60, null=True)),
                ('service_provider_d', models.CharField(blank=True, max_length=60, null=True)),
                ('institute_c', models.CharField(blank=True, max_length=60, null=True)),
                ('institute_r', models.CharField(blank=True, max_length=60, null=True)),
                ('institute_u', models.CharField(blank=True, max_length=60, null=True)),
                ('institute_d', models.CharField(blank=True, max_length=60, null=True)),
                ('active_status', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
    ]
