# Generated by Django 3.2.5 on 2022-01-22 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0032_auto_20220122_0524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uni',
            old_name='HSCReq',
            new_name='HSCReqPG',
        ),
        migrations.AddField(
            model_name='uni',
            name='HSCReqUG',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='uni',
            name='mobile',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
