# Generated by Django 3.2.5 on 2022-01-22 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0033_auto_20220122_0547'),
    ]

    operations = [
        migrations.AddField(
            model_name='uni',
            name='MinDeposit',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='uni',
            name='UGReq',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
