# Generated by Django 3.2.5 on 2022-01-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0034_auto_20220122_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='uni',
            name='PGExtra',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='uni',
            name='UGExtra',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
