# Generated by Django 3.2.5 on 2022-03-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0035_auto_20220122_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='DesiredSubject',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='StudyDestination',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='birth_date',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='birth_month',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='birth_year',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='country',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='gender',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='prev_qualification',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
