# Generated by Django 3.2.5 on 2022-03-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0036_auto_20220308_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='HSCGPA',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
