# Generated by Django 3.2.5 on 2022-03-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0037_students_hscgpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='UGCGPA',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
