# Generated by Django 3.2.5 on 2022-03-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0039_bachelorcert_bachelormarksheet_bachelortranscript_banksolvency_cv_hsccert_hsctranscript_lor1_lor2_lo'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='prev_status',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
