# Generated by Django 3.2.5 on 2022-03-22 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0040_application_prev_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='prev_status',
        ),
    ]
