# Generated by Django 3.2.5 on 2022-03-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0042_newslettercampaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslettercampaign',
            name='message',
            field=models.CharField(blank=True, max_length=30000, null=True),
        ),
    ]
