# Generated by Django 3.2.5 on 2022-03-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0043_alter_newslettercampaign_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('recipient', models.CharField(blank=True, max_length=60, null=True)),
                ('message', models.CharField(blank=True, max_length=30000, null=True)),
            ],
        ),
    ]
